apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  selector:
    matchLabels:
      app: api-gateway-pod
  replicas: 1
  template: #template for pods
    #we don't need a name under metatdata for the
    #pod but a label is needed since selectors rely on them
    metadata:
      labels:
        app: api-gateway-pod
    spec:
      containers:
        - name: fleetman-api-gateway
          image: richardchesterwood/k8s-fleetman-api-gateway:release2
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice
#to deploy the pod to kubectl : - kubectl apply -f <deployment file name>

#to view rollout of a deployment - kubectl rollout status deploy <deployment name>

#to view rollout history of a deployment - kubectl rollout history deploy <deployment name>

#to  rollout to  a previous version of a deployment - kubectl rollout undo deploy <deployment name> --to-revision=<revion name>

#view deployment info :- kubectl describe <deployment name>

#Execute command in kubernetes pod :- kubectl exec <pod name> <command e.g ls>

#Interact with shell on pods container :- kubectl -it exec <container name> sh
