apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  #This defines which pods are going to be represented by this service
  #The service becomes a network endpoint for either other service or maybe external uses to connect to e.g browser
  selector:
    app: fleetman-position-tracker
  # use below (ports and type) configuration to ensure that your app port
  # is only exposed to the internal cluster and not the outside world
  ports:
    - name: http #optional
      port: 8080
  type: ClusterIP
# to deploy the service to kubectl : - kubectl apply -f <service_filename>
# view service info :- kubectl describe <service name>
