# use this when deploying to cloud
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: fleetman-queue-pod
  ports:
    #external port accessible to the internet
    - name: http
      port: 8161
    #internal port to the cluster
    - name: endpoint
      port: 61616
  type: ClusterIP
# to deploy the service to kubectl : - kubectl apply -f <service_filename>
# view service info :- kubectl describe <service name>
