apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue-service
spec:
  selector:
    app: fleetman-queue-pod
  ports:
  - name: http
    port: 8161
    nodePort: 30010
  type: NodePort

# to deploy the service to kubectl : - kubectl apply -f <service_filename>
# view service info :- kubectl describe <service name>
