apiVersion: v1
kind: Pod
metadata:
  name: fleetman-queue-pod
  labels:
    name: fleetman-queue-pod
spec:
  containers:
  - name: fleetman-queue
    image: richardchesterwood/k8s-fleetman-queue:release1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
