apiVersion: v1
kind: Pod
metadata:
  name: fleetman-queue-pod
  labels:
    name: fleetman-queue-pod
spec:
  containers:
    - name: fleetman-queue
      image: richardchesterwood/k8s-fleetman-queue:release1
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
# to deploy the pod to kubectl : - kubectl apply -f first-pod.yaml

#view pod info :- kubectl describe <pod name>

#Execute command in kubernetes pod :- kubectl exec <pod name> <command e.g ls>

#Interact with shell on pods container :- kubectl -it exec <container name> sh

#To view logs :-  kubectl logs -f <pod name/id>
