apiVersion: v1
kind: Pod
metadata:
  name: fleetman-webapp-pod
  labels:
    app: fleetman-webapp-pod
spec:
  containers:
    - name: fleetman-webapp
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
      resources:
        memory: "128Mi"
        cpu: "300m"
        limits:
          memory: "300Mi"
          cpu: "500m"

# The resources limits(resources limit section) should be the same or higher than the resourses requests (resources - request section)
# Requests are important to help the scheduler make intelligent decisions on which node to place the pod
# Limits are important to prevent the container from taking up all the memory in a cluster node since this can lead to cluster failure


# to deploy the pod to kubectl : - kubectl apply -f first-pod.yaml

#view pod info :- kubectl describe <pod name>

#Execute command in kubernetes pod :- kubectl exec <pod name> <command e.g ls>

#Interact with shell on pods container :- kubectl -it exec <container name> sh

#To view logs :-  kubectl logs <pod name/id>

# Get pods with more information e.g the actual node the pod is running in :- kubectl get pods -o wide